import type { RunResult, Sample, ModelSpec, Category } from './types';
import {
  clusterModels,
  categoryTotals,
  categoryDeltas,
  costTable,
  contentAdjusted,
} from './report';

// Shape of output/results.json as written by src/index.ts.
export interface ResultsFile {
  source?: string;
  generatedNote?: string;
  models: ModelSpec[];
  samples: Array<{ id: string; category: Category }>;
  result: RunResult;
}

// A corpus sample's real text, looked up by id for the input index.
export interface CorpusEntry {
  category: Category;
  text: string;
}

function fenceLang(category: Category): string {
  if (category === 'json') return 'json';
  if (category === 'code') return '';
  return 'text';
}

function tokensOf(result: RunResult, model: string, sampleId: string): number | null {
  return (
    result.measurements.find((m) => m.model === model && m.sampleId === sampleId)?.tokens ?? null
  );
}

/**
 * Build a self-contained Markdown report from a parsed results.json plus the
 * corpus text (for the input index). The index is keyed off the samples that
 * are ACTUALLY in the run, so the report always matches the data; any corpus
 * sample missing from the run is flagged rather than silently included.
 */
export function buildReportMarkdown(data: ResultsFile, corpus: Map<string, CorpusEntry>): string {
  const { models, result } = data;

  // Reconstruct Sample[] for the samples actually in the run (order preserved).
  // Text comes from the corpus where available; report.ts helpers only need id
  // and category, so a missing text is harmless for the analysis.
  const runSamples: Sample[] = data.samples.map((s) => ({
    id: s.id,
    category: s.category,
    text: corpus.get(s.id)?.text ?? '',
  }));

  const cats = [...new Set(runSamples.map((s) => s.category))];
  const overhead = new Map(result.overhead.map((o) => [o.model, o.tokens]));

  const lines: string[] = [];
  const push = (s = '') => lines.push(s);

  push('# hakari — Tokenizer Measurement Report');
  push();
  push('Generated by `npm run report` from `output/results.json`.');
  push(
    'Metric: gross real-world input tokens (fixed per-request overhead included), from the Anthropic `count_tokens` endpoint — no generation.',
  );
  push();
  push(`- Models measured: **${models.length}**`);
  push(`- Samples measured: **${runSamples.length}**`);
  if (data.generatedNote) push(`- ${data.generatedNote}`);
  push();

  // Consistency check between the corpus and the run.
  const runIds = new Set(runSamples.map((s) => s.id));
  const corpusExtra = [...corpus.keys()].filter((id) => !runIds.has(id));
  const missingText = runSamples.filter((s) => !corpus.has(s.id)).map((s) => s.id);
  if (corpusExtra.length > 0 || missingText.length > 0) {
    push('> **Consistency check**');
    if (corpusExtra.length > 0) {
      push('>');
      push(
        `> The corpus contains ${corpusExtra.length} sample(s) not in this run: \`${corpusExtra.join(
          '`, `',
        )}\`. Re-run \`npm run experiment\`, then \`npm run report\`, to include them.`,
      );
    }
    if (missingText.length > 0) {
      push('>');
      push(
        `> These run samples have no matching corpus text (index shows a placeholder): \`${missingText.join(
          '`, `',
        )}\`.`,
      );
    }
    push();
  }

  // === Token matrix ===
  push('## Token counts (gross)');
  push();
  push('Rows are samples; columns are models. Values include the fixed per-request overhead.');
  push();
  push(`| sample | ${models.map((m) => m.id).join(' | ')} |`);
  push(`| --- | ${models.map(() => '---:').join(' | ')} |`);
  for (const s of runSamples) {
    const cells = models.map((m) => {
      const t = tokensOf(result, m.id, s.id);
      return t === null ? 'ERR' : String(t);
    });
    push(`| ${s.id} | ${cells.join(' | ')} |`);
  }
  push();

  // === Overhead ===
  push('## Per-request overhead');
  push();
  push(
    'Fixed tokens each model adds per request (measured by counting the single character "a"). Included in every count above.',
  );
  push();
  push('| model | overhead |');
  push('| --- | ---: |');
  for (const m of models) {
    const v = overhead.get(m.id);
    push(`| ${m.id} | ${v === null || v === undefined ? 'ERR' : v} |`);
  }
  push();

  // === Gross clusters ===
  const grossClusters = clusterModels(result, models, runSamples);
  push('## Tokenizer clusters — gross tokens');
  push();
  push('Models whose gross token vectors are identical across every sample. Overhead shown as `[oh=N]`.');
  push();
  grossClusters.forEach((c, i) => {
    const members = c.models.map((id) => `${id}[oh=${overhead.get(id) ?? 'ERR'}]`).join(', ');
    push(`- **Cluster ${i + 1}:** ${members}`);
  });
  const grossClustered = new Set(grossClusters.flatMap((c) => c.models));
  const incomplete = models.map((m) => m.id).filter((id) => !grossClustered.has(id));
  if (incomplete.length > 0) push(`- _Incomplete (errors, not clustered):_ ${incomplete.join(', ')}`);
  push();

  // === Content clusters (overhead subtracted) ===
  const contentResult = contentAdjusted(result);
  const contentClusters = clusterModels(contentResult, models, runSamples);
  const contentVec = (modelId: string): (number | null)[] =>
    runSamples.map((s) => tokensOf(contentResult, modelId, s.id));

  push('## Tokenizer clusters — content only (overhead subtracted)');
  push();
  push(
    "Clustering after subtracting each model's fixed overhead. This isolates the tokenizer from request scaffolding: models that share a tokenizer but wrap requests differently merge here even if they split on gross tokens.",
  );
  push();
  contentClusters.forEach((c, i) => {
    push(`- **Cluster ${i + 1}:** ${c.models.join(', ')}`);
  });
  push();

  // Near-identical content clusters: differ on only one or two samples.
  interface NearMiss {
    a: string[];
    b: string[];
    diffs: Array<{ sampleId: string; av: number | null; bv: number | null }>;
    maxAbs: number;
  }
  const nearMisses: NearMiss[] = [];
  for (let i = 0; i < contentClusters.length; i++) {
    for (let j = i + 1; j < contentClusters.length; j++) {
      const av = contentVec(contentClusters[i].models[0]);
      const bv = contentVec(contentClusters[j].models[0]);
      const diffs: NearMiss['diffs'] = [];
      let maxAbs = 0;
      runSamples.forEach((s, k) => {
        if (av[k] !== bv[k]) {
          diffs.push({ sampleId: s.id, av: av[k], bv: bv[k] });
          if (av[k] !== null && bv[k] !== null) {
            maxAbs = Math.max(maxAbs, Math.abs((av[k] as number) - (bv[k] as number)));
          }
        }
      });
      if (diffs.length > 0 && diffs.length <= 2) {
        nearMisses.push({ a: contentClusters[i].models, b: contentClusters[j].models, diffs, maxAbs });
      }
    }
  }
  if (nearMisses.length > 0) {
    push('### Near-identical tokenizers');
    push();
    push(
      'Content clusters that differ on only one or two samples — almost certainly the same underlying tokenizer, kept apart by a tiny difference (and, on gross tokens, by differing overhead).',
    );
    push();
    for (const nm of nearMisses) {
      const detail = nm.diffs.map((d) => `\`${d.sampleId}\` (${d.av} vs ${d.bv})`).join('; ');
      push(
        `- **{${nm.a.join(', ')}}** ≈ **{${nm.b.join(', ')}}** — differ on ${nm.diffs.length} of ${
          runSamples.length
        } sample(s), max Δ ${nm.maxAbs} token(s): ${detail}.`,
      );
    }
    push();
  }

  if (contentClusters.length < grossClusters.length) {
    push(
      `> Content clustering collapsed **${grossClusters.length}** gross clusters into **${contentClusters.length}** — the extra gross splits were overhead differences, not tokenization.`,
    );
  } else if (nearMisses.length > 0) {
    push(
      '> Gross and content clustering have the same number of groups, but the near-identical pairs above show some "separate" clusters are effectively one tokenizer, differing on a sample or two (and by overhead on gross tokens).',
    );
  } else {
    push(
      '> Gross and content clustering agree and no clusters are near-identical — the partition looks clean.',
    );
  }
  push();

  // === Category deltas ===
  push('## Per-category token delta between clusters');
  push();
  const delta = categoryDeltas(result, models, runSamples);
  if (delta.baselineModels.length === 0 || delta.comparisons.length === 0) {
    push('_Need at least two complete clusters to compute a delta._');
  } else {
    push(
      `Baseline (lightest) cluster: \`${delta.baselineModels.join(
        ', ',
      )}\`. Each row is another cluster's tokens per category as a percentage above/below baseline.`,
    );
    push();
    push(`| cluster | ${cats.join(' | ')} |`);
    push(`| --- | ${cats.map(() => '---:').join(' | ')} |`);
    for (const cmp of delta.comparisons) {
      const cells = cats.map((c) => {
        const d = cmp.deltaPct.get(c);
        return d === null || d === undefined ? 'n/a' : `${d >= 0 ? '+' : ''}${d.toFixed(1)}%`;
      });
      push(`| ${cmp.models.join(', ')} | ${cells.join(' | ')} |`);
    }
  }
  push();

  // === Cost ===
  push('## Input cost per model (all measured samples summed)');
  push();
  push(
    "Total input tokens times each model's cached input price. Models that tokenize identically but price differently reveal pure cost overhead.",
  );
  push();
  push('| model | tokens | $/1M | cost (USD) |');
  push('| --- | ---: | ---: | ---: |');
  const rows = costTable(result, models);
  for (const m of models) {
    const mr = rows.filter((r) => r.model === m.id);
    const tokens = mr.reduce((a, r) => a + r.tokens, 0);
    const dollars = mr.reduce((a, r) => a + r.dollars, 0);
    push(`| ${m.id} | ${tokens} | $${m.inputPricePerMillion} | $${dollars.toFixed(8)} |`);
  }
  push();

  // === Appendix: input index ===
  push('## Appendix — input index (the actual text measured)');
  push();
  for (const s of runSamples) {
    const entry = corpus.get(s.id);
    const chars = entry ? [...entry.text].length : 0;
    push(`### \`${s.id}\` — ${s.category}${entry ? ` · ${chars} chars` : ''}`);
    push();
    if (entry) {
      push('```' + fenceLang(s.category));
      push(entry.text);
      push('```');
    } else {
      push('_(text unavailable — sample not in current corpus)_');
    }
    push();
  }

  // === Caveats ===
  push('## Caveats');
  push();
  push(
    '- Pricing is cached (see `src/models.ts`) and must be re-verified before quoting real costs; intro rates expire.',
  );
  push('- Counts are specific to the corpus in `src/corpus.ts`; this report reflects only the samples in the input index above.');
  push('- Counts come from `count_tokens` (no generation) — the exact input tokens Anthropic would bill for these messages.');
  push();

  return lines.join('\n');
}
